services:
  backend:
    build:
      context: backend
    container_name: flask-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: frontend
    container_name: vite-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
